/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReadyzRouteImport } from './routes/readyz'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfigErrorRouteImport } from './routes/config-error'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as VerifyEmailTokenRouteImport } from './routes/verify-email.$token'
import { Route as RpcSplatRouteImport } from './routes/rpc.$'
import { Route as ProfileTabRouteImport } from './routes/profile.$tab'
import { Route as InviteCodeRouteImport } from './routes/invite.$code'
import { Route as DashboardUsersRouteImport } from './routes/dashboard.users'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardProfilesRouteImport } from './routes/dashboard.profiles'
import { Route as DashboardInvitesRouteImport } from './routes/dashboard.invites'
import { Route as DashboardHistoryRouteImport } from './routes/dashboard.history'
import { Route as BrandingAssetRouteImport } from './routes/branding.$asset'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard.settings.index'
import { Route as DashboardSettingsSettingsTabRouteImport } from './routes/dashboard.settings.$settingsTab'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadyzRoute = ReadyzRouteImport.update({
  id: '/readyz',
  path: '/readyz',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigErrorRoute = ConfigErrorRouteImport.update({
  id: '/config-error',
  path: '/config-error',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const VerifyEmailTokenRoute = VerifyEmailTokenRouteImport.update({
  id: '/verify-email/$token',
  path: '/verify-email/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RpcSplatRoute = RpcSplatRouteImport.update({
  id: '/rpc/$',
  path: '/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileTabRoute = ProfileTabRouteImport.update({
  id: '/$tab',
  path: '/$tab',
  getParentRoute: () => ProfileRoute,
} as any)
const InviteCodeRoute = InviteCodeRouteImport.update({
  id: '/invite/$code',
  path: '/invite/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfilesRoute = DashboardProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInvitesRoute = DashboardInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHistoryRoute = DashboardHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardRoute,
} as any)
const BrandingAssetRoute = BrandingAssetRouteImport.update({
  id: '/branding/$asset',
  path: '/branding/$asset',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSettingsRoute,
} as any)
const DashboardSettingsSettingsTabRoute =
  DashboardSettingsSettingsTabRouteImport.update({
    id: '/$settingsTab',
    path: '/$settingsTab',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/config-error': typeof ConfigErrorRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/healthz': typeof HealthzRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRouteWithChildren
  '/readyz': typeof ReadyzRoute
  '/reset-password': typeof ResetPasswordRoute
  '/branding/$asset': typeof BrandingAssetRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/invites': typeof DashboardInvitesRoute
  '/dashboard/profiles': typeof DashboardProfilesRoute
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard/users': typeof DashboardUsersRoute
  '/invite/$code': typeof InviteCodeRoute
  '/profile/$tab': typeof ProfileTabRoute
  '/rpc/$': typeof RpcSplatRoute
  '/verify-email/$token': typeof VerifyEmailTokenRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/dashboard/settings/$settingsTab': typeof DashboardSettingsSettingsTabRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/config-error': typeof ConfigErrorRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/healthz': typeof HealthzRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/readyz': typeof ReadyzRoute
  '/reset-password': typeof ResetPasswordRoute
  '/branding/$asset': typeof BrandingAssetRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/invites': typeof DashboardInvitesRoute
  '/dashboard/profiles': typeof DashboardProfilesRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/invite/$code': typeof InviteCodeRoute
  '/profile/$tab': typeof ProfileTabRoute
  '/rpc/$': typeof RpcSplatRoute
  '/verify-email/$token': typeof VerifyEmailTokenRoute
  '/dashboard': typeof DashboardIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/dashboard/settings/$settingsTab': typeof DashboardSettingsSettingsTabRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/config-error': typeof ConfigErrorRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/healthz': typeof HealthzRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRouteWithChildren
  '/readyz': typeof ReadyzRoute
  '/reset-password': typeof ResetPasswordRoute
  '/branding/$asset': typeof BrandingAssetRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/invites': typeof DashboardInvitesRoute
  '/dashboard/profiles': typeof DashboardProfilesRoute
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard/users': typeof DashboardUsersRoute
  '/invite/$code': typeof InviteCodeRoute
  '/profile/$tab': typeof ProfileTabRoute
  '/rpc/$': typeof RpcSplatRoute
  '/verify-email/$token': typeof VerifyEmailTokenRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/dashboard/settings/$settingsTab': typeof DashboardSettingsSettingsTabRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/config-error'
    | '/dashboard'
    | '/forgot-password'
    | '/healthz'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/readyz'
    | '/reset-password'
    | '/branding/$asset'
    | '/dashboard/history'
    | '/dashboard/invites'
    | '/dashboard/profiles'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/invite/$code'
    | '/profile/$tab'
    | '/rpc/$'
    | '/verify-email/$token'
    | '/dashboard/'
    | '/profile/'
    | '/dashboard/settings/$settingsTab'
    | '/dashboard/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/config-error'
    | '/forgot-password'
    | '/healthz'
    | '/login'
    | '/onboarding'
    | '/readyz'
    | '/reset-password'
    | '/branding/$asset'
    | '/dashboard/history'
    | '/dashboard/invites'
    | '/dashboard/profiles'
    | '/dashboard/users'
    | '/invite/$code'
    | '/profile/$tab'
    | '/rpc/$'
    | '/verify-email/$token'
    | '/dashboard'
    | '/profile'
    | '/dashboard/settings/$settingsTab'
    | '/dashboard/settings'
  id:
    | '__root__'
    | '/'
    | '/config-error'
    | '/dashboard'
    | '/forgot-password'
    | '/healthz'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/readyz'
    | '/reset-password'
    | '/branding/$asset'
    | '/dashboard/history'
    | '/dashboard/invites'
    | '/dashboard/profiles'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/invite/$code'
    | '/profile/$tab'
    | '/rpc/$'
    | '/verify-email/$token'
    | '/dashboard/'
    | '/profile/'
    | '/dashboard/settings/$settingsTab'
    | '/dashboard/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfigErrorRoute: typeof ConfigErrorRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HealthzRoute: typeof HealthzRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  ReadyzRoute: typeof ReadyzRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  BrandingAssetRoute: typeof BrandingAssetRoute
  InviteCodeRoute: typeof InviteCodeRoute
  RpcSplatRoute: typeof RpcSplatRoute
  VerifyEmailTokenRoute: typeof VerifyEmailTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readyz': {
      id: '/readyz'
      path: '/readyz'
      fullPath: '/readyz'
      preLoaderRoute: typeof ReadyzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config-error': {
      id: '/config-error'
      path: '/config-error'
      fullPath: '/config-error'
      preLoaderRoute: typeof ConfigErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/verify-email/$token': {
      id: '/verify-email/$token'
      path: '/verify-email/$token'
      fullPath: '/verify-email/$token'
      preLoaderRoute: typeof VerifyEmailTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rpc/$': {
      id: '/rpc/$'
      path: '/rpc/$'
      fullPath: '/rpc/$'
      preLoaderRoute: typeof RpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$tab': {
      id: '/profile/$tab'
      path: '/$tab'
      fullPath: '/profile/$tab'
      preLoaderRoute: typeof ProfileTabRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/invite/$code': {
      id: '/invite/$code'
      path: '/invite/$code'
      fullPath: '/invite/$code'
      preLoaderRoute: typeof InviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profiles': {
      id: '/dashboard/profiles'
      path: '/profiles'
      fullPath: '/dashboard/profiles'
      preLoaderRoute: typeof DashboardProfilesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/invites': {
      id: '/dashboard/invites'
      path: '/invites'
      fullPath: '/dashboard/invites'
      preLoaderRoute: typeof DashboardInvitesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/history': {
      id: '/dashboard/history'
      path: '/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof DashboardHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/branding/$asset': {
      id: '/branding/$asset'
      path: '/branding/$asset'
      fullPath: '/branding/$asset'
      preLoaderRoute: typeof BrandingAssetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/$settingsTab': {
      id: '/dashboard/settings/$settingsTab'
      path: '/$settingsTab'
      fullPath: '/dashboard/settings/$settingsTab'
      preLoaderRoute: typeof DashboardSettingsSettingsTabRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
  }
}

interface DashboardSettingsRouteChildren {
  DashboardSettingsSettingsTabRoute: typeof DashboardSettingsSettingsTabRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardSettingsRouteChildren: DashboardSettingsRouteChildren = {
  DashboardSettingsSettingsTabRoute: DashboardSettingsSettingsTabRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
}

const DashboardSettingsRouteWithChildren =
  DashboardSettingsRoute._addFileChildren(DashboardSettingsRouteChildren)

interface DashboardRouteChildren {
  DashboardHistoryRoute: typeof DashboardHistoryRoute
  DashboardInvitesRoute: typeof DashboardInvitesRoute
  DashboardProfilesRoute: typeof DashboardProfilesRoute
  DashboardSettingsRoute: typeof DashboardSettingsRouteWithChildren
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardHistoryRoute: DashboardHistoryRoute,
  DashboardInvitesRoute: DashboardInvitesRoute,
  DashboardProfilesRoute: DashboardProfilesRoute,
  DashboardSettingsRoute: DashboardSettingsRouteWithChildren,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ProfileRouteChildren {
  ProfileTabRoute: typeof ProfileTabRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileTabRoute: ProfileTabRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfigErrorRoute: ConfigErrorRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HealthzRoute: HealthzRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRouteWithChildren,
  ReadyzRoute: ReadyzRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  BrandingAssetRoute: BrandingAssetRoute,
  InviteCodeRoute: InviteCodeRoute,
  RpcSplatRoute: RpcSplatRoute,
  VerifyEmailTokenRoute: VerifyEmailTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
